# Generated by Django 5.0.6 on 2024-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanbatch',
            name='batch_mention',
            field=models.TextField(blank=True, null=True),
        ),
    ]
