# Generated by Django 5.0.6 on 2024-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_alter_cleanbatch_batch_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanbatchlog',
            name='process',
            field=models.TextField(blank=True, null=True),
        ),
    ]
