# Generated by Django 5.0.6 on 2024-09-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_alter_cleanbatchlog_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanbatchlog',
            name='process',
            field=models.TextField(default='0'),
        ),
    ]
