"""
Django settings for my_sop project.

Generated by 'django-admin startproject' using Django 2.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-f4qc84e++2gxp#z+c9nj0m6tpq654a+4%io5d9sjg!z@b8mba'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','www.zxy-console.cn','zxy-console.cn','nint.zxy-console.cn', 'localhost', '127.0.0.1']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    'http://117.72.45.190:3000',
    'https://117.72.45.190:3000',
    'http://sop.zxy-console.cn',
    'https://sop.zxy-console.cn',
    'http://10.21.90.130',
    'http://10.21.200.200',
    'http://127.0.0.1',
]

APPEND_SLASH  = False
# Application definition
WEBSOCKET_URL = '/ws/'
WEBSOCKET_ALLOW_ALL_ORIGINS = True
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'django_rq',
    'sop',
    'cleaning',
    'report',
]

RQ_QUEUES = {
    'default': {
        'HOST': '117.72.45.190',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 36000,
        'PASSWORD': 'nint'
    },
    'report': {
        'HOST': '117.72.45.190',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 108000,
        'PASSWORD': 'nint'
    },
    'report130': {
        'HOST': '117.72.45.190',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 108000,
        'PASSWORD': 'nint',
        'WORKER_CLASS': 'rq.SimpleWorker'
    },
}

# Celery configuration
CELERY_BROKER_URL = 'redis://:nint@117.72.45.190:6379/0'
CELERY_RESULT_BACKEND = 'redis://:nint@117.72.45.190:6379/0'
CELERY_TASK_RESULT_EXPIRES = None
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'

MIDDLEWARE = [
    # 'my_sop.middleware.simple_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'my_sop.middleware.LoginRequiredMiddleware',  # 替换为实际路径
    # 'websocket.middleware.WebSocketMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'my_sop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '../sop/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 配置redis信息
CHANNEL_LAYERS = {
    'default':{
        "BACKEND" : "channels_redis.core.RedisChannelLayer",
    },
}

WSGI_APPLICATION = 'my_sop.wsgi.application'
ASGI_APPLICATION = 'my_sop.asgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_sop',
        'USER': 'zeng.xiangyan',
        'PASSWORD': 'Nint@2024',
        'HOST': '10.21.200.200',
        # 'USER': 'zxy',
        # 'PASSWORD': '13639054279zxy',
        # 'HOST': '10.21.90.130',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 36000,
        },
        'CONN_MAX_AGE':3600
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
}

LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'

# USE_I18N = True

# USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
LOGIN_URL='/admin/login/'

WECHAT_CORP_ID = 'wwae2c132f1c16f837'
WECHAT_AGENT_ID = '1000002'
WECHAT_SECRET = 'eZbsQYfQ4MjJXDl7MRYvxBFpbuLe8zzkGLPOz673Qjs'

