# Generated by Django 5.0.6 on 2024-10-29 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='check_fss_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default=0)),
                ('tbl', models.CharField(max_length=100)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('status', models.IntegerField()),
                ('rank', models.IntegerField(default=0)),
                ('msg', models.TextField(default='')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('PersonInCharge', models.CharField(max_length=100, verbose_name='负责人')),
                ('param', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='report_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchId', models.CharField(max_length=50)),
                ('UseModel', models.CharField(max_length=255)),
                ('ReportName', models.CharField(max_length=255)),
                ('DateRange', models.CharField(max_length=50)),
                ('Status', models.IntegerField()),
                ('UpdateTime', models.DateTimeField()),
                ('PersonInCharge', models.CharField(max_length=100, verbose_name='当前负责人')),
                ('fileUrl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='viewed_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.PositiveIntegerField(default=0, verbose_name='eid')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.PositiveIntegerField(choices=[(1, '普通属性'), (2, '度量属性(聚合值)')], default=1, verbose_name='type')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='rank')),
                ('state', models.PositiveIntegerField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='state')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('db', models.CharField(max_length=100)),
                ('sql_query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedquery',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_title'),
        ),
    ]
