# Generated by Django 5.0.6 on 2025-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_task',
            name='TaskId',
            field=models.IntegerField(default=0),
        ),
    ]
