# Generated by Django 5.0.6 on 2025-05-16 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_report_task_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_task',
            name='UpdateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
