# Generated by Django 5.0.6 on 2024-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0003_auto_20231127_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_fss_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default=0)),
                ('tbl', models.CharField(max_length=100)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('status', models.IntegerField()),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('PersonInCharge', models.CharField(max_length=100, verbose_name='负责人')),
                ('param', models.CharField(max_length=255)),
            ],
        ),
    ]
