# Generated by Django 5.0.6 on 2024-06-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0004_check_fss_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_fss_task',
            name='msg',
            field=models.TextField(default=''),
        ),
    ]
