# Generated by Django 5.0.6 on 2024-06-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0005_check_fss_task_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_fss_task',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
