# Generated by Django 5.0.6 on 2024-06-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0006_check_fss_task_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_fss_task',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
