# Generated by Django 5.0.6 on 2024-10-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0009_savedquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedquery',
            name='name',
        ),
    ]
