# Generated by Django 5.0.6 on 2024-10-27 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0010_remove_savedquery_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedquery',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_title'),
        ),
    ]
