h_eid_ref = {
    6: [91783, 'all_brand_91783', 'entity_prod_91783_E', ['`uuid`','`uuid2`','`sign`','`ver`','`old_uuid`','`old_uuid2`','`old_sign`','`old_ver`','`pkey`','`date`','`cid`','`real_cid`','`item_id`','`sku_id`','`name`','`sid`','`shop_type`','`brand`','`all_bid`','`alias_all_bid`','`region_str`','`price`','`org_price`','`promo_price`','`img`','`sales`','`num`','`trade_props.name`','`trade_props.value`','`trade_props_hash`','`source`','`clean_cid`','`clean_pid`','`clean_props.name`','`clean_props.value`','`alias_pid`','`created`'],
            " and 1" #4
    ],
    # 20109: [91130, 'all_brand_91130', 'entity_prod_91130_E_GSK', ['`uuid`','`sign`','`ver`','`pkey`','`date`','`cid`','`real_cid`','`item_id`','`sku_id`','`name`','`sid`','`shop_type`','`brand`','`rbid`','`all_bid`','`alias_all_bid`','`sub_brand`','`region`','`region_str`','`price`','`org_price`','`promo_price`','`trade`','`num`','`sales`','`img`','`trade_props.name`','`trade_props.value`','`props.name`','`props.value`','`tip`','`source`','`created`','`trade_props_hash`','`trade_props_arr`','`clean_props.name`','`clean_props.value`','`clean_alias_all_bid`','`clean_all_bid`','`clean_cid`','`clean_num`','`clean_pid`','`clean_price`','`clean_sales`','`clean_sku_id`','`clean_time`','`clean_ver`','`old_alias_all_bid`','`old_all_bid`','`old_num`','`old_sales`','`old_sign`','`old_uuid`','`old_ver`','`alias_pid`','`clean_split_rate`','`clean_type`','`spSKU`','`spSKU件数`','`sptype（仅SKU答题）`','`sp产品类别`','`sp产地`','`sp人群`','`sp内包装`','`sp剂型`','`sp功能`','`sp单品数`','`sp单品规格`','`sp口味`','`sp品牌`','`sp复合种类`','`sp婴童年龄段`','`sp子品类`','`sp孕期阶段`','`sp店铺分类`','`sp总规格`','`sp总销量`','`sp拆分前SKU名`','`sp是否含微量元素/矿物质`','`sp是否套包`','`sp是否孕产哺乳保健`','`sp是否无效链接`','`sp机洗答题子品类对不上`','`sp每日服用次数`','`sp每次服用量(g/ml，无颗数才答)`','`sp每次服用颗/粒/片数`','`sp清洗交易属性`','`sp生产商`','`sp百洋SKU名称`','`sp百洋SKU规格详情`','`sp百洋人群`','`sp百洋分类`','`sp百洋剂型`','`sp百洋子品类`','`sp百洋是否女性专用`','`sp种类`','`sp药保属性`','`sp辅助-宝贝名判断品牌`','`sp辅助_人群`','`sp辅助_单品数（片）`','`sp辅助_单品数（瓶）`','`sp辅助_单品数（粒）`','`sp辅助_单品数（袋）`','`sp辅助_单品规格（g）`','`sp辅助_单品规格（ml）`','`sp辅助_品牌划分`','`sp辅助_复合维生素种类1`','`sp辅助_复合维生素种类2`','`sp辅助_复合维生素种类3`','`sp辅助_子品类划分`','`sp辅助_总规格（g）`','`sp辅助_总规格（ml）`','`sp是否人工答题`','`sp疑似新品`','`spBLK_人群`','`spBLK_婴童年龄段`','`spBLK_孕期阶段`','`sp辅助_多选人群划分`','`sp清洗检查`','`sp套包宝贝`','`sp答题检查辅助字段`','`sp单一成分`','`sp复合成分`','`clean_brush_id`','`sp人工修正价格`','`sp辅助-抖音bid`','`sp辅助-抖音brand`','`sp辅助-抖音category`','`sp辅助-抖音子品类`','`sp是否含有复维`','`sp是否含有益生菌`','`spGSK-子品类`','`sp是否含有复维-人工`','`sp是否含有复维-机洗`','`sp是否含有益生菌-机洗`'],
    #         " and `spGSK-子品类`!=''" #4
    # ],
    26396: [91010, 'all_brand_91010', 'entity_prod_91010_E_GSK', ['`uuid`','`sign`','`ver`','`pkey`','`date`','`cid`','`real_cid`','`item_id`','`sku_id`','`name`','`sid`','`shop_type`','`brand`','`rbid`','`all_bid`','`alias_all_bid`','`sub_brand`','`region`','`region_str`','`price`','`org_price`','`promo_price`','`trade`','`num`','`sales`','`img`','`trade_props.name`','`trade_props.value`','`props.name`','`props.value`','`tip`','`source`','`created`','`trade_props_hash`','`trade_props_arr`','`clean_props.name`','`clean_props.value`','`clean_alias_all_bid`','`clean_all_bid`','`clean_cid`','`clean_num`','`clean_pid`','`clean_price`','`clean_sales`','`clean_sku_id`','`clean_time`','`clean_ver`','`old_alias_all_bid`','`old_all_bid`','`old_num`','`old_sales`','`old_sign`','`old_uuid`','`old_ver`','`alias_pid`','`clean_brush_id`','`clean_split_rate`','`clean_type`','`sp产地`','`sp件数(sku维度)`','`sp价格段`','`sp保修期`','`sp假牙清洁片数`','`sp充电模式`','`sp净含量（ml）`','`sp功效`','`sp包装形式`','`sp单只净含量（g）`','`sp口味`','`sp品牌(不出数)`','`sp型号`','`sp子品类`','`sp总件数(宝贝维度)`','`sp总净含量(g)(sku维度)`','`sp总净含量(宝贝维度)`','`sp成分`','`sp是否人工答题`','`sp是否保护牙龈`','`sp是否加固牙齿`','`sp是否含氟`','`sp是否啫喱状`','`sp是否套包`','`sp是否抗敏感`','`sp是否无效链接`','`sp是否智能`','`sp是否清新口气`','`sp是否清火/防上火`','`sp是否美白牙齿`','`sp是否防止蛀牙`','`sp牙刷类型`','`sp类别`','`sp系列`','`sp辅助-抖音bid`','`sp辅助-抖音brand`','`sp辅助-抖音category`','`sp辅助-抖音cid`','`sp辅助_是否含牙膏`','`sp适用人群`','`sp颜色`','`sp是否检查`','`sp辅助-牙膏品类判断`','`sp套包宝贝`','`sp店铺分类`','`sp疑似新品`','`sp是否中草药`','`sp是否多功能`','`sp辅助_品牌划分`'],
            " and `sp子品类` in ('牙膏', '口腔护理套装(含牙膏)')" #4
    ],
    # 20018: [91081, 'all_brand_91081', 'entity_prod_91081_E_MDLZ_report', ['`uuid`','`sign`','`ver`','`pkey`','`date`','`cid`','`real_cid`','`item_id`','`sku_id`','`name`','`sid`','`shop_type`','`brand`','`all_bid`','`alias_all_bid`','`region_str`','`price`','`org_price`','`promo_price`','`num`','`sales`','`img`','`trade_props.name`','`trade_props.value`','`source`','`created`','`trade_props_hash`','`clean_props.name`','`clean_props.value`','`clean_cid`','`clean_pid`','`clean_sku_id`','`old_alias_all_bid`','`old_all_bid`','`old_num`','`old_sales`','`old_sign`','`old_uuid`','`old_ver`','`alias_pid`','`clean_split_rate`','`clean_brush_id`'],
    # " and `clean_props.value`[indexOf(`clean_props.name`, '子品类')]='饼干'" #4
    # ],
    # 1020018: [91843, 'all_brand_91843', 'entity_prod_91843_E', ['`uuid`','`uuid2`','`sign`','`ver`','`pkey`','`date`','`cid`','`real_cid`','`item_id`','`sku_id`','`name`','`sid`','`shop_type`','`brand`','`rbid`','`all_bid`','`alias_all_bid`','`sub_brand`','`region`','`region_str`','`price`','`org_price`','`promo_price`','`trade`','`num`','`sales`','`img`','`trade_props.name`','`trade_props.value`','`props.name`','`props.value`','`tip`','`source`','`created`','`trade_props_hash`','`trade_props_arr`','`clean_props.name`','`clean_props.value`','`clean_alias_all_bid`','`clean_all_bid`','`clean_cid`','`clean_num`','`clean_pid`','`clean_price`','`clean_sales`','`clean_sku_id`','`clean_split_rate`','`clean_type`','`clean_time`','`clean_ver`','`old_alias_all_bid`','`old_all_bid`','`old_num`','`old_sales`','`old_sign`','`old_uuid`','`old_uuid2`','`old_ver`','`alias_pid`','`spSKU-件数出数专用`','`spSKU（不出数）`','`sp价格带`','`sp分类`','`sp加热方式`','`sp包数`','`sp包装规格`','`sp单sku包数`','`sp单包规格`','`sp即食面种类`','`sp厂商`','`sp口味`','`sp口味交叉分析`','`sp品牌`','`sp地域特色`','`sp套包混搭`','`sp子品类`','`sp子品类（人工）`','`sp子系列`','`sp店铺类型`','`sp异国风味`','`sp总规格`','`sp方便面/类方便面种类`','`sp方便食品种类`','`sp是否包含XO酱`','`sp是否包含五香`','`sp是否包含其它辣`','`sp是否包含其它酸`','`sp是否包含其它非酸非辣`','`sp是否包含冬阴功`','`sp是否包含刺激辣`','`sp是否包含剁椒`','`sp是否包含卤香`','`sp是否包含咖喱`','`sp是否包含椒麻`','`sp是否包含油泼辣子`','`sp是否包含泡椒`','`sp是否包含泡菜`','`sp是否包含红油`','`sp是否包含红烧`','`sp是否包含罗宋`','`sp是否包含胡椒味`','`sp是否包含葱香`','`sp是否包含辣卤香`','`sp是否包含辣白菜`','`sp是否包含酸汤`','`sp是否包含酸菜`','`sp是否包含酸辣`','`sp是否包含香辣`','`sp是否包含鸡汁`','`sp是否包含麻油`','`sp是否包含麻辣`','`sp是否素食面`','`sp是否进口`','`sp生产国`','`sp种类`','`sp系列`','`sp辅助_关键词判断包装规格`','`sp辅助_包装单位判断包装规格`','`sp辅助_包装数量判断混合包装规格`','`sp辅助_单包数`','`sp辅助_总包数`','`sp辅助_机洗方便面种类`','`sp面饼制程`','`sp面饼种类`','`sp食材`','`sp食用方式`','`sp是否人工答题`','`sp套包宝贝`','`sp店铺分类`','`sp疑似新品`','`clean_brush_id`'],
    # " and 1" #4
    # ],
    # 20018: [91024, 'all_brand_91024', 'entity_prod_91024_E', ['`uuid`','`sign`','`ver`','`pkey`','`date`','`cid`','`real_cid`','`item_id`','`sku_id`','`name`','`sid`','`shop_type`','`brand`','`all_bid`','`alias_all_bid`','`region_str`','`price`','`org_price`','`promo_price`','`num`','`sales`','`img`','`trade_props.name`','`trade_props.value`','`source`','`created`','`trade_props_hash`','`clean_props.name`','`clean_props.value`','`clean_cid`','`clean_pid`','`clean_sku_id`','`old_alias_all_bid`','`old_all_bid`','`old_num`','`old_sales`','`old_sign`','`old_uuid`','`old_ver`','`alias_pid`','`clean_split_rate`','`clean_brush_id`'],
    # " and `sp子品类`='巧克力'"],
}